"""Готовые уровни (запечены заранее). Показываются в случайном порядке.

Отредактированы в editor.py. Каждый элемент LEVELS — карта уровня
(список строк одинаковой длины).
Легенда: X/I/J/K/L/Q/U/V/W/Y/Z блоки  P старт  f фрукт  S пила  ^ шип  E флаг
  T трамплин  F огонь  N вентилятор  O шип.шар  R/H давилки
  A стрела  B ящик  M платформа  D пад.платформа  C чекпоинт  g лампа
"""

LEVELS = [
    [
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJ      g      YYY        JJ',
        'JJJJ     f f f f YYYf f f   JJ',
        'JJJJ             YYY      E JJ',
        'JJJJ     XXXBBBBBYYYBBIIIIIIIJ',
        'JJJJ     XXX     YYYBBIIIIIIIJ',
        'JJJJBBBBBXXX     YYY    g   JJ',
        'JJJJBBBBBXXX     YYYff      JJ',
        'JJJJ     XXXf     g         JJ',
        'JJYY     XXXf            XXXJJ',
        'JJYY   XXXXXXXX      T XXXXXJJ',
        'JJYY P XXXXXXXXXXX   XXXXXXXJJ',
        'IIIIIIIXXXXXXXXIIIIIIIIIIIIIII',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    ],
    [
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'II   g    f   gf      g    JII',
        'II                 f  f     II',
        'II      ^^  ^^  ^         E II',
        'IJJ ff JJJJJJJJLLLJJ     LLLKK',
        'IJJ ff JJJJJJJJLLLJJ f   LLLKK',
        'II        g  JJLLL g     LLLKK',
        'II        f    LLLf      LLLKK',
        'II       f f   LLL   f   LLLKK',
        'II      f f f  LLLf      LLLKK',
        'II             LLL       LLLKK',
        'IIJ  N       P LLLLL^N^LLLLLKK',
        'KKKKKKKKKKKKKKKLLLLLKKKKKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    ],
    [
        ' JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        ' JJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        ' JJ gf      g        g      II',
        'JJJ fff    f f f f  f f     II',
        'JJJ Ef                      II',
        'JJQQQQLLL        M LLLLL    II',
        'JJQQQQLLL          LLLLL    II',
        'JJQQQQYY           LLgLL    II',
        'JJQQQQYg           LL LL    II',
        'JJQQQQ ff          LL LL  M II',
        'JJQQQQ fff         LLLLL    II',
        'JJQQQQ ffff      M LLLLL P  II',
        'JJQYQQQQQfff     LLLLLYLLLLLLI',
        'JJIIIIIIIIIIIIIIIIILLLYYLLYLLI',
        'JJIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    ],
    [
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII ',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII ',
        'II g        g         g      II ',
        'II R               R         II ',
        'II             f f f f f     II ',
        'II f QQQQQQ   YYYYYYYYYYWW   II ',
        'II f QQQQQQ   YYYYYYYYYYWW   II ',
        'II f QQ  QQ   gf f f f f g   II ',
        'II f QQ  QQ        R         II ',
        'II f QQ  QQ                E II ',
        'IIff QQQQQQQQQQQQQQQQQQYYYYYQQKK',
        'II f QQQQQQQQQQQQQQQQQQYYYYYQQKK',
        'II f   g   WW  gf fgf  g    QQKK',
        'II         WW  f f f f    P QQKK',
        'II    QQQ                QQQQQKK',
        'II   QQQQ R              KKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKK    ',
    ],
    [
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'II      g     YYY  YYY    g   JJ',
        'II H          YY    YY      H JJ',
        'II   f f f    YY     g    f   JJ',
        'II  f f f f   YY              JJ',
        'II            g          f    JJ',
        'II                 XXX        JJ',
        'II                 XXX    f   JJ',
        'IXXXXXXXXXXXXX     XXX        JJ',
        'JXXXXXXXXXXXXX     XXXg  f    JJ',
        'JJY  g       g     XXX        JJ',
        'JJ f f f f f f    PXXX    f   JJ',
        'JJ               XXXXX H      JJ',
        'JJ             H XXXXX   YY E JJ',
        'JJ               XXXXXXXXXXXXXJJ',
        'JJIIIIIIIIIIIIIXXXXXYXXXXXYYXXII',
        'JJIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    ],
    [
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'II  g      g         S     YYYJJ',
        'II                         g YJJ',
        'II                            JJ',
        'II P                          JJ',
        'IIJJJ     S                   JJ',
        'II  g  LLLLLLL     XXXX       JJ',
        'II     LLLLLLL     XXXXS      JJ',
        'IIJJ   LLLLLLL     XXXX       JJ',
        'II     LLLLLLL   YYYXXX f f f JJ',
        'II       gS      gYXXXXJJ     JJ',
        'IIY                XXXX g f f JJ',
        'ILLLLL             XXXX  f    JJ',
        'ILYYLL            YXXXXX  f f JJ',
        'ILYYLLLLL    Y  XXXXXXXXXX E  JJ',
        'IIIIIIIIIIIIIIIIXXXXXYYIIIIIIIJJ',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJ',
    ],
    [
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'KKVV      g     VVVVVV     g  JJ',
        'KKVV               g          JJ',
        'KK g                        f JJ',
        'KK                ff       f fJJ',
        'KK         f     f  f       E JJ',
        'KKf f     f f   f    f     QQQQK',
        'KK      ^^        ^^       QQQQK',
        'KKVVV   VVVVV   QQQQQQ     QQQQK',
        'KK g      g     QQQQQQ     QQQQK',
        'KK              QQ  QQ f   QQQQK',
        'KK              QQ VQQ     QQQQK',
        'KK P    ^^^^^^^^QQQQQQ f   QQQQK',
        'KYYYYYYYQQQQQQQQQQQQQQ   QQQQQQK',
        'KYYYYYYYQQQQQQQQQQVQQQQQQQQQQQQK',
        'KKKKKKKKKKKKKKKKKKKKKKQQQQQKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    ],
    [
        ' JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        ' JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        ' JJYY     g      g    g    g  II',
        ' JJYY                         II',
        ' JJ g     f     f             II',
        ' JJ      f f f f f f          II',
        ' JJ         f f   f f         II',
        ' JJ                        E YII',
        'JJJ       D     D         XXXXII',
        'JJJ P        D     D      XXXXII',
        'JJXXXXX                   XXXXII',
        'JJXXXXX                   XXXXII',
        'JJXXXXX                   XXXXII',
        'JJXXXXX                  YXXXXII',
        'JJXXYXXXX              XXXXXXYII',
        'JJXYYXYXXXX         XXXXXXXXYYII',
        'JJIIIIIIIIIIIIIIIIIIXXXXXXXXYYII',
        'JJIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    ],
    [
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
        '                                ',
    ],
    [
        'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                                                                                                                YY',
        'YY                 S      f  f  f                S      f  f  f                S      f  f  f                     YY',
        'YY              f  fH f  YYYYYYYYY          H f  f  f  YYYYYYYYY    H       f  f  f  YYYYYYYYY                    YY',
        'YY    f  f  f  YYYYYYYYY     g      f  f  f  YYYYYYYYY            f  f  f  YYYYYYYYY     g      f  f  f           YY',
        'YY   YYYYYYYYY Y                   YYYYYYYYY     g     Y         YYYYYYYYY Y                   YYYYYYYYY          YY',
        'YY       g     A                         A                         A g                       A                    YY',
        'YY P    f   ^^   fC       f  ^^    f  T  C  f ^^     f    F   f^^      f     B  f      C f       ^^        f    E YY',
        'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
    ],
    [
        'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
        'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                                                                                                                    ZZ',
        'ZZ                           S                                                  S                                     ZZ',
        'ZZ                     f f f f f f f                                      f f f f f f f                               ZZ',
        'ZZ    f f f f f f f   ZZZZZZZZZZZZZZZZ                   f f f f f f f   ZZZZZZZZZZZZZZZZ                             ZZ',
        'ZZ   ZZZZZZZZZZZZZZZZ                   f f f f f f f   ZZZZZZZZZZZZZZZZ        g          f f f f f f f              ZZ',
        'ZZ          g         O                ZZZZZZZZZZZZZZZZ                         O         ZZZZZZZZZZZZZZZZ            ZZ',
        'ZZ             A                         A    g                    A                         A                        ZZ',
        'ZZ P    f   ^^   fC       f  ^^    f    TC  f ^^     f      F f^^      f        f      C f       ^^        f        E ZZ',
        'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
        'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
        'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ',
    ],
    [
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                                                                        XX',
        'XX                                                                     S                                                  XX',
        'XX                        S                                       f f f f f f                                             XX',
        'XX                   f f f f f f                                 XXXXXXXXXXXXXX                 f f f f f f               XX',
        'XX                  XXXXXXXXXXXXXX                 f f f f f f         g                       XXXXXXXXXXXXXX             XX',
        'XX    f f f f f f               M                 XXXXXXXXXXXXXX    M            f f fMf f f         g  M                 XX',
        'XX   XXXXXXXXXXXXXX                 f f f f f f                                 XXXXXXXXXXXXXX                            XX',
        'XX         g          O            XXXXXXXXXXXXXX  O                            O                            O            XX',
        'XX             A                         g                         A                         A                            XX',
        'XX P    f   ^^   fC       f  ^^    f     T  f ^^     f        f^^      f        f B    C f       ^^        f  C     f   E XX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    [
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                                                                                                                            II',
        'II                       S        f f f f f f                      S        f f f f f f                      S                II',
        'II                  f f f f f f  IIIIIIIIIIIII                f f f f f f  IIIIIIIIIIIII                f f f f f f           II',
        'II    f f f f f f  IIIIIIIIIIIII       g        f f f f f f  IIIIIIIIIIIII                f f f f f f  IIIIIIIIIIIII          II',
        'II   IIIIIIIIIIIII I  O     R                  IIIIIIIIIIIII       g       I    O        IIIIIIIIIIIII I     O                II',
        'II         g   A                         A                         A                         A g                              II',
        'II P    f   ^^   fC       f  ^^    f     CT f ^^     f        f^^      f        f    B C f       ^^        f  C   ^^f       E II',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
        'IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII',
    ],
    [
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                                                                                                                JJ',
        'JJ                                           f f f f f                                                        f f f f f           JJ',
        'JJ    f f f f f                             JJJJJJJJJJJJ               f f f f f                     S       JJJJJJJJJJJJ         JJ',
        'JJ   JJJJJJJJJJJJ               f f f f f                     S       JJJJJJJJJJJJ               f f f f f        g               JJ',
        'JJ        g            S       JJJJJJJJJJJJ               f f f f f                             JJJJJJJJJJJJ                      JJ',
        'JJ                Df f f f f        g   D                JJJJJJJJJJJJ               f f f f f             D                       JJ',
        'JJ                JJJJJJJJJJJJ                     O       R  g                 O  JJJJJJJJJJJJ              O                    JJ',
        'JJ             A                         A                         A                    g    A                         A          JJ',
        'JJ P    f   ^^   fC       f  ^^    f     C  f ^^     f        f^^ F    f        f      CBf       ^^        f  C   ^^f           E JJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
        'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
    ],
    [
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK                                                                                                                                    KK',
        'KK    f  f  f                             f  f  f                             f  f  f                             f  f  f             KK',
        'KK   KKKKKKKKKKK    H S       f  f  f    KKKKKKKKKKK      S       f Hf  f    KKKKKKKKKKK    H S       f  f  f    KKKKKKKKKKK          KK',
        'KK        g       f  f  f    KKKKKKKKKKK              f  f  f    KKKKKKKKKKK      g       f  f  f    KKKKKKKKKKK                      KK',
        'KK               KKKKKKKKKKKR     g      K         O KKKKKKKKKKK K              O        KKKKKKKKKKK      g  O   K       R            KK',
        'KK             A                         A                g        A                         A                         A              KK',
        'KK P    f   ^^   fC       f  ^^    f     C  fT^^     f        f^^   F  f        f      C fB      ^^        f  C   ^^f        f      E KK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
    ],
]

LEVEL_ROUTES = [
    {},
    {},
    {(26, 9): {'path': [(0, 0), (0, -4)]}, (17, 5): {'path': [(0, 0), (-7, 0)]}, (17, 11): {'path': [(0, 0), (0, -4)]}},
    {(24, 14): {'path': [(0, 0), (-15, 0), (-15, 0), (-14, 0), (-14, 0), (-14, 0)]}, (23, 14): {'path': [(0, 0), (-14, 0)]}, (23, 15): {'path': [(0, 0), (-14, 0), (-13, 0), (-13, 0), (-13, 0), (-14, 0), (-14, 0)]}, (24, 15): {'path': [(0, 0), (-14, 0), (-15, 0)]}, (10, 14): {'path': [(0, 0), (14, 0)]}, (10, 15): {'path': [(0, 0), (14, 0)]}, (9, 14): {'path': [(0, 0), (14, 0)]}, (9, 15): {'path': [(0, 0), (14, 0)]}, (3, 14): {'path': [(0, 0), (0, -11), (9, -6)]}, (3, 3): {'path': [(0, 0), (0, 11)]}, (12, 8): {'path': [(0, 0), (0, -5), (15, -5), (15, 0), (0, -5)]}, (27, 3): {'path': [(0, 0), (0, 5), (0, 5)]}, (12, 3): {'path': [(0, 0), (15, 0)]}, (27, 8): {'path': [(0, 0), (-15, 0)]}, (19, 3): {'path': [(0, 0), (8, 0), (8, 5), (-7, 5), (-7, 0)]}, (19, 8): {'path': [(0, 0), (-7, 0), (-7, -5), (8, -5), (8, 0)]}},
    {(15, 14): {'path': [(0, 0), (-12, 0)]}, (3, 3): {'path': [(0, 0), (9, 0), (9, 4), (0, 4)]}, (28, 3): {'path': [(0, 0), (0, 10)]}, (23, 13): {'path': [(0, 0), (0, -10)]}},
    {(14, 11): {'path': [(0, 0), (0, -5), (-8, -5), (-8, 0), (0, -5)]}, (10, 11): {'path': [(0, 0), (4, 0), (4, -5), (-4, -5), (-4, 0)]}, (10, 6): {'path': [(0, 0), (-4, 0), (-4, 5), (4, 5), (4, 0)]}, (21, 2): {'path': [(0, 0), (0, 4)]}, (23, 8): {'path': [(0, 0), (6, 0)]}},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
]

LEVEL_TILE_OVERRIDES = [
    {},
    {(27, 12): (5, 8), (27, 11): (5, 8), (27, 10): (5, 8), (27, 9): (5, 8), (27, 8): (5, 8), (27, 7): (5, 8), (27, 6): (5, 8), (27, 5): (5, 8), (26, 5): (5, 8), (25, 5): (5, 8), (25, 6): (5, 8), (25, 7): (5, 8), (25, 8): (5, 8), (25, 9): (5, 8), (25, 10): (5, 8), (25, 11): (5, 8), (25, 12): (5, 8), (26, 12): (5, 8), (26, 11): (5, 8), (26, 10): (5, 8), (26, 6): (5, 8), (26, 7): (5, 8), (26, 8): (5, 8), (26, 9): (5, 8)},
    {},
    {},
    {},
    {},
    {(7, 16): (0, 0), (6, 16): (0, 0), (5, 16): (0, 0), (4, 16): (0, 0), (3, 16): (0, 0), (2, 16): (0, 0), (1, 16): (0, 0)},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
]

LEVEL_ROTATIONS = [
    {},
    {(27, 2): 270, (2, 12): 90},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
]
